### ISSUE TITLE
Environment

### ISSUE THREAD

**Issue by li-ruidong** [uccproc/gns4demdesign#1]
HI, can the authors provide some information about the environment?

**Comment by uccproc** [comment]
Main packages used in the environment has been added. See [here](https://github.com/uccproc/gns4demdesign/blob/main/environment.txt)

**Comment by li-ruidong** [comment]
I am still unable to replicate the environment successfully. Would it be possible for the authors to provide a .yml file for easier setup or directly sharing the environment file? Thank you very much!
